services:
  lunatune-api:
    build: .
    container_name: lunatune-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - .env
    restart: unless-stopped
